# TickWatch configuration

# How often the scoreboard updates (in ticks, 20 == 1 second)
update-interval-ticks: 20

# How often TPS monitor runs (ticks)
tps-monitor-interval: 1200 # 60s

# TPS value below which a log entry will be written
tps-threshold: 18.0

# Which metrics to show on the scoreboard
show:
  cpu: true
  ram: true
  disk: true