name: TickWatchRealms
version: 1.1.0
main: com.epsilonrealms.tickwatch.Main
api-version: 1.21.8
description: Shows live TPS & Ping with toggleable sidebar (ops only)
commands:
  status:
    description: Shows current TPS and your Ping
    usage: /status
  toggleboard:
    description: Toggle the TPS/Ping scoreboard (ops only)
    usage: /toggleboard
    permission: tickwatch.toggle
permission:
  tickwatch.toggle:
    default: op